name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches_ignore: []

jobs:

  # Define the job to run before your matrix job
  get-python-versions:
    runs-on: ubuntu-latest
    outputs:
      python-matrix: ${{ steps.get-python-versions-action.outputs.latest-python-versions }}
    steps:
    - uses: snok/latest-python-versions@v1
      id: get-python-versions-action
      with:
        min-version: 3.12
        max-version: 3.13.0

  test:
    needs: [get-python-versions]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # TODO cyvcf2 0.31.1 does not yet support python 3.13
        python-version: ["3.12"]  # ${{ fromJson(needs.get-python-versions.outputs.python-matrix) }}
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          # Install a specific version of uv and enable caching.
          version: "0.6.2"
          enable-cache: true

      - name: Set up Python
        run: uv python install ${{ matrix.python-version }}

      - name: Install the project
        run: uv sync --all-extras --dev --frozen

      - name: Setup tox-uv
        run: uv tool install tox --with tox-uv

      - name: Check formatting
        run: uv run tox -e format-check

      - name: Linting
        run: uv run tox -e lints

      - name: Run mypy
        run: uv run tox -e mypy

      - name: Run tests
        run: uv run tox -e py${{ matrix.python-version }}